version: '3.9'
services:
  api:
    container_name: nest_api
    build: .
    ports:
      - '5001:5001'
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - PORT=${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
